"""The pre-commit hook refuses a hand-edited projects block in AGENTS.md."""
import os
import subprocess
from pathlib import Path

import pytest

HOOK = Path(__file__).with_name("pre-commit")
START = "<!-- ops:projects start — generated by ops-projects; edit identity.toml in the project, or identity-mirror.toml in ops -->"
PREVIOUS = "<!-- ops:projects start — generated by ops-projects; edit identity-mirror.toml in ops -->"
END = "<!-- ops:projects end -->"
BLOCK = f"{START}\n## Projects\n\n- `ai` — agent config\n{END}"


def sh(cwd, *args, **kw):
    return subprocess.run(args, cwd=cwd, check=True, text=True, capture_output=True, **kw).stdout


DOCS_OK = "#!/usr/bin/env python3\nimport sys\nassert sys.argv[1:] == ['check']\n"


def docs_stub(repo, body=DOCS_OK):
    tool = repo / "tools" / "ops-docs"
    tool.parent.mkdir(exist_ok=True)
    tool.write_text(body)
    tool.chmod(0o755)


@pytest.fixture
def world(tmp_path):
    """A fake ops checkout whose ops-projects renders BLOCK, a registry naming it, and an ai repo."""
    ops = tmp_path / "ops"
    (ops / "bin").mkdir(parents=True)
    stub = ops / "bin" / "ops-projects"
    stub.write_text("#!/usr/bin/env python3\nimport sys\nassert sys.argv[1] == 'render'\n"
                    f"print({BLOCK!r})\n")
    stub.chmod(0o755)
    config = tmp_path / "config" / "tasks"
    config.mkdir(parents=True)
    (config / "projects.toml").write_text(f'[projects]\nops = "{ops}"\nai = "{tmp_path / "ai"}"\n')
    repo = tmp_path / "ai"
    repo.mkdir()
    sh(repo, "git", "init", "-q")
    sh(repo, "git", "config", "user.email", "t@example.com")
    sh(repo, "git", "config", "user.name", "t")
    (repo / "AGENTS.md").write_text(f"# rules\n\n{BLOCK}\n")
    docs_stub(repo)
    sh(repo, "git", "add", "AGENTS.md")
    sh(repo, "git", "commit", "-q", "-m", "init")
    env = {**os.environ, "XDG_CONFIG_HOME": str(tmp_path / "config")}
    return repo, env, tmp_path


def run_hook(repo, env):
    return subprocess.run([str(HOOK)], cwd=repo, env=env, text=True, capture_output=True)


def test_passes_when_staged_block_matches_render(world):
    repo, env, _ = world
    (repo / "AGENTS.md").write_text(f"# rules, edited\n\n{BLOCK}\n")
    sh(repo, "git", "add", "AGENTS.md")
    r = run_hook(repo, env)
    assert r.returncode == 0, r.stderr


def test_accepts_the_previous_marker_while_ops_still_renders_it(world):
    repo, env, tmp = world
    old = BLOCK.replace(START, PREVIOUS)
    stub = tmp / "ops" / "bin" / "ops-projects"
    stub.write_text("#!/usr/bin/env python3\nimport sys\nassert sys.argv[1] == 'render'\n"
                    f"print({old!r})\n")
    (repo / "AGENTS.md").write_text(f"# rules, edited\n\n{BLOCK}\n")
    sh(repo, "git", "add", "AGENTS.md")
    assert run_hook(repo, env).returncode == 0


def test_marker_bridge_replaces_only_the_start_marker(world):
    repo, env, tmp = world
    old = BLOCK.replace(START, PREVIOUS)
    old = old.replace(END, f"{PREVIOUS}\n{END}")
    current = old.replace(PREVIOUS, START, 1)
    stub = tmp / "ops" / "bin" / "ops-projects"
    stub.write_text("#!/usr/bin/env python3\nimport sys\nassert sys.argv[1] == 'render'\n"
                    f"print({old!r})\n")
    (repo / "AGENTS.md").write_text(f"# rules, edited\n\n{current}\n")
    sh(repo, "git", "add", "AGENTS.md")
    assert run_hook(repo, env).returncode == 0


def test_refuses_a_hand_edited_block(world):
    repo, env, _ = world
    edited = BLOCK.replace("- `ai` — agent config", "- `ai` — agent config\n- `zz` — hand-written")
    (repo / "AGENTS.md").write_text(f"# rules\n\n{edited}\n")
    sh(repo, "git", "add", "AGENTS.md")
    r = run_hook(repo, env)
    assert r.returncode == 1
    assert "identity-mirror.toml" in r.stderr and "+- `zz`" in r.stderr
    assert "differs from ops-projects render" in r.stderr


def test_judges_the_staged_content_not_the_worktree(world):
    repo, env, _ = world
    (repo / "AGENTS.md").write_text(f"# rules\n\n{BLOCK}\n")
    sh(repo, "git", "add", "AGENTS.md")
    (repo / "AGENTS.md").write_text("# rules\n\nblock removed on disk only\n")
    assert run_hook(repo, env).returncode == 0


def test_skips_when_agents_md_is_not_staged(world):
    repo, env, _ = world
    (repo / "other.txt").write_text("x\n")
    sh(repo, "git", "add", "other.txt")
    (repo / "AGENTS.md").write_text("# drifted on disk but unstaged\n")
    assert run_hook(repo, env).returncode == 0


def test_refuses_a_staged_agents_md_without_markers(world):
    repo, env, _ = world
    (repo / "AGENTS.md").write_text("# rules\n\nno block\n")
    sh(repo, "git", "add", "AGENTS.md")
    r = run_hook(repo, env)
    assert r.returncode == 1 and "markers" in r.stderr


def test_fails_loudly_when_ops_is_unregistered(world):
    repo, env, tmp = world
    (tmp / "config" / "tasks" / "projects.toml").write_text(f'[projects]\nai = "{repo}"\n')
    (repo / "AGENTS.md").write_text(f"# rules, edited\n\n{BLOCK}\n")
    sh(repo, "git", "add", "AGENTS.md")
    r = run_hook(repo, env)
    assert r.returncode == 1 and "ops" in r.stderr and "registered" in r.stderr


def test_fails_loudly_when_registry_is_missing(world):
    repo, env, tmp = world
    (tmp / "config" / "tasks" / "projects.toml").unlink()
    (repo / "AGENTS.md").write_text(f"# rules, edited\n\n{BLOCK}\n")
    sh(repo, "git", "add", "AGENTS.md")
    r = run_hook(repo, env)
    assert r.returncode == 1 and "projects.toml" in r.stderr


def test_refuses_a_staged_deletion_cleanly(world):
    repo, env, _ = world
    sh(repo, "git", "rm", "-q", "AGENTS.md")
    r = run_hook(repo, env)
    assert r.returncode == 1 and "deletion" in r.stderr and "Traceback" not in r.stderr


def test_fails_loudly_when_ops_projects_is_missing(world):
    repo, env, tmp = world
    (tmp / "ops" / "bin" / "ops-projects").unlink()
    (repo / "AGENTS.md").write_text(f"# rules, edited\n\n{BLOCK}\n")
    sh(repo, "git", "add", "AGENTS.md")
    r = run_hook(repo, env)
    assert r.returncode == 1 and "ops-projects" in r.stderr and "not found" in r.stderr


def test_fails_loudly_when_render_fails(world):
    repo, env, tmp = world
    stub = tmp / "ops" / "bin" / "ops-projects"
    stub.write_text("#!/usr/bin/env python3\nimport sys\nsys.stderr.write('ops-projects: bad identity-mirror.toml\\n')\nsys.exit(1)\n")
    (repo / "AGENTS.md").write_text(f"# rules, edited\n\n{BLOCK}\n")
    sh(repo, "git", "add", "AGENTS.md")
    r = run_hook(repo, env)
    assert r.returncode == 1 and "render failed" in r.stderr and "bad identity-mirror.toml" in r.stderr


def test_runs_the_docs_check_and_fails_with_its_output(world):
    repo, env, _ = world
    docs_stub(repo, "#!/usr/bin/env python3\nimport sys\nsys.stderr.write('ops-docs: README.md: identity region is missing\\n')\nsys.exit(1)\n")
    result = run_hook(repo, env)
    assert result.returncode == 1
    assert "identity region is missing" in result.stderr
    assert "just docs" in result.stderr


def test_runs_the_docs_check_when_agents_md_is_not_staged(world):
    repo, env, _ = world
    docs_stub(repo, "#!/usr/bin/env python3\nimport sys\nsys.exit(1)\n")
    (repo / "README.md").write_text("x\n")
    sh(repo, "git", "add", "README.md")
    assert run_hook(repo, env).returncode == 1


def test_fails_loudly_when_ops_docs_is_missing(world):
    repo, env, _ = world
    (repo / "tools" / "ops-docs").unlink()
    result = run_hook(repo, env)
    assert result.returncode == 1
    assert "tools/ops-docs" in result.stderr


def test_refuses_a_force_added_local_file(world):
    repo, env, _ = world
    (repo / ".gitignore").write_text("local/\n")
    (repo / "local").mkdir()
    (repo / "local" / "settings.work.json").write_text("{}\n")
    sh(repo, "git", "add", "-f", "local/settings.work.json")
    result = run_hook(repo, env)
    assert result.returncode == 1
    assert "local/settings.work.json" in result.stderr


def test_refuses_a_rename_into_local(world):
    repo, env, _ = world
    (repo / "settings.work.json").write_text("{}\n")
    sh(repo, "git", "add", "settings.work.json")
    sh(repo, "git", "commit", "-q", "-m", "tracked")
    (repo / "local").mkdir()
    sh(repo, "git", "mv", "settings.work.json", "local/settings.work.json")
    result = run_hook(repo, env)
    assert result.returncode == 1
    assert "local/settings.work.json" in result.stderr


def test_passes_when_nothing_under_local_is_staged(world):
    repo, env, _ = world
    (repo / "notes.md").write_text("x\n")
    sh(repo, "git", "add", "notes.md")
    assert run_hook(repo, env).returncode == 0
